# Generated by Django 5.2 on 2025-05-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Female", "Female"), ("Male", "Male")],
                max_length=50,
                null=True,
            ),
        ),
    ]
