# Generated by Django 5.2 on 2025-05-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
