# Generated by Django 5.2 on 2025-05-15 10:23

import social.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_post_hashtags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.post_image_path
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=social.models.profile_image_path
            ),
        ),
    ]
